//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Categories.
        /// </summary>
        public static string allcategories {
            get {
                return ResourceManager.GetString("allcategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant.
        /// </summary>
        public static string applicantFound {
            get {
                return ResourceManager.GetString("applicantFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicants.
        /// </summary>
        public static string applicantsFound {
            get {
                return ResourceManager.GetString("applicantsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string backtolist {
            get {
                return ResourceManager.GetString("backtolist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banking.
        /// </summary>
        public static string Banking {
            get {
                return ResourceManager.GetString("Banking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is Required.
        /// </summary>
        public static string CityRequired {
            get {
                return ResourceManager.GetString("CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Description.
        /// </summary>
        public static string CompanyDescription {
            get {
                return ResourceManager.GetString("CompanyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name is Required.
        /// </summary>
        public static string CompanyNameRequired {
            get {
                return ResourceManager.GetString("CompanyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string confirmPass {
            get {
                return ResourceManager.GetString("confirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords not matching.
        /// </summary>
        public static string ConfirmPassRequired {
            get {
                return ResourceManager.GetString("ConfirmPassRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction.
        /// </summary>
        public static string Construction {
            get {
                return ResourceManager.GetString("Construction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send your comments.
        /// </summary>
        public static string contactComments {
            get {
                return ResourceManager.GetString("contactComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string contactContact {
            get {
                return ResourceManager.GetString("contactContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string contactLocation {
            get {
                return ResourceManager.GetString("contactLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        public static string createAcc {
            get {
                return ResourceManager.GetString("createAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string deletebtn {
            get {
                return ResourceManager.GetString("deletebtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string deleteconf {
            get {
                return ResourceManager.GetString("deleteconf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string detailsbtn {
            get {
                return ResourceManager.GetString("detailsbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string editbtn {
            get {
                return ResourceManager.GetString("editbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is Required.
        /// </summary>
        public static string FromEmailRequired {
            get {
                return ResourceManager.GetString("FromEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name is Required.
        /// </summary>
        public static string FromNameRequired {
            get {
                return ResourceManager.GetString("FromNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Technology.
        /// </summary>
        public static string InformationTechnology {
            get {
                return ResourceManager.GetString("InformationTechnology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Position and press Enter.
        /// </summary>
        public static string insertsearch {
            get {
                return ResourceManager.GetString("insertsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Description.
        /// </summary>
        public static string JobDescription {
            get {
                return ResourceManager.GetString("JobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Found.
        /// </summary>
        public static string jobFound {
            get {
                return ResourceManager.GetString("jobFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs Found.
        /// </summary>
        public static string jobsFound {
            get {
                return ResourceManager.GetString("jobsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max 50 characters allowed.
        /// </summary>
        public static string Long50 {
            get {
                return ResourceManager.GetString("Long50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max 50 characters allowed.
        /// </summary>
        public static string Long500 {
            get {
                return ResourceManager.GetString("Long500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min 6 characters.
        /// </summary>
        public static string LongPass100 {
            get {
                return ResourceManager.GetString("LongPass100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        public static string Marketing {
            get {
                return ResourceManager.GetString("Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string menuContact {
            get {
                return ResourceManager.GetString("menuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string menuHome {
            get {
                return ResourceManager.GetString("menuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        public static string menuJobs {
            get {
                return ResourceManager.GetString("menuJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message is Required.
        /// </summary>
        public static string MessageRequired {
            get {
                return ResourceManager.GetString("MessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Listings.
        /// </summary>
        public static string myJobsmenu {
            get {
                return ResourceManager.GetString("myJobsmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Match Found.
        /// </summary>
        public static string noMatch {
            get {
                return ResourceManager.GetString("noMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string pagerOf {
            get {
                return ResourceManager.GetString("pagerOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string pagerPage {
            get {
                return ResourceManager.GetString("pagerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string pass {
            get {
                return ResourceManager.GetString("pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is Required.
        /// </summary>
        public static string PassRequired {
            get {
                return ResourceManager.GetString("PassRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position is Required.
        /// </summary>
        public static string PositionRequired {
            get {
                return ResourceManager.GetString("PositionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string postJob {
            get {
                return ResourceManager.GetString("postJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail.
        /// </summary>
        public static string Retail {
            get {
                return ResourceManager.GetString("Retail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string savebtn {
            get {
                return ResourceManager.GetString("savebtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchBtn {
            get {
                return ResourceManager.GetString("SearchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by City.
        /// </summary>
        public static string searchbycity {
            get {
                return ResourceManager.GetString("searchbycity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Position.
        /// </summary>
        public static string searchbyposition {
            get {
                return ResourceManager.GetString("searchbyposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for Job?.
        /// </summary>
        public static string searchingforjob {
            get {
                return ResourceManager.GetString("searchingforjob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string sendBtn {
            get {
                return ResourceManager.GetString("sendBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills &amp; Requirements.
        /// </summary>
        public static string SkillsRequirements {
            get {
                return ResourceManager.GetString("SkillsRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit CV.
        /// </summary>
        public static string submitCV {
            get {
                return ResourceManager.GetString("submitCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to log in..
        /// </summary>
        public static string useAnotherService {
            get {
                return ResourceManager.GetString("useAnotherService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string useLocalAccLogin {
            get {
                return ResourceManager.GetString("useLocalAccLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Job.
        /// </summary>
        public static string viewJob {
            get {
                return ResourceManager.GetString("viewJob", resourceCulture);
            }
        }
    }
}
